### ISSUE TITLE
Пример веб-интерфейса, работающего на Tsakorpus

### ISSUE THREAD

**Issue by Iskander1220** [timarkh/tsakorpus#16]
Здравствуйте, Тимофей! Имеется ли какой-нибудь онлайн-пример, работающий на основе платформы Tsakorpus, чтобы можно было потестировать возможности поиска?

**UPD:** Нашёл — https://tsakorpus.readthedocs.io/en/latest/examples.html

**Comment by timarkh** [comment]
Отлично, тогда закрываю. :)
