### ISSUE TITLE
Regular expressions for 'gramm_shortcuts'

### ISSUE THREAD

**Issue by ansorox** [timarkh/tsakorpus#6]
Для параметра 'gramm_shortcuts' в файле corpus.json не работают регулярные выражения.  Наверное, они там и не подразумевались, но это очень удобно устроено для параметра 'gloss_shortcuts', и если бы регулярки можно было использовать и для грамматических тегов, было бы здорово.

Например, хотелось бы, чтобы по тегу "A" искались такие А, в которых нет пометы NtoV, а по тегу, например, "А+" искались бы уже все А без ограничений (то есть NtoV в такую выдачу бы включалось). Первое правило со скриншота ниже не работает, а второе работает нормально.

![0](https://user-images.githubusercontent.com/22198377/195147301-098eb181-bf6b-4bef-8ac5-fbcd8f779806.png)

Правила с разделителями тоже не работают, например, такое: 

![1](https://user-images.githubusercontent.com/22198377/195147282-eecf9910-c7b4-4c36-abca-352958036ebe.png)

**Comment by timarkh** [comment]
Что касается именно регулярных выражений, то они в ``gramm_shortcuts`` работать не могут принципиально, потому что поиск по грамтэгам -- это поиск по ключевым словам, а не полнотекстовый (это работает намного быстрее, потому что их ограниченное количество). Но логические выражения с конъюнкцией, дизъюнкцией, отрицанием и скобками действительно должны бы работать. Кажется, я это починил.

Из приведённых примеров в первом выражении ошибка (вместо ``&`` по правилам цакорпуса должна быть запятая). Если её исправить, всё теперь вроде бы должно работать.
