### ISSUE TITLE
Listing lemmas with gram. features in corpora without alt. analyses

### ISSUE THREAD

**Issue by sarkipo** [timarkh/tsakorpus#7]
When searching for a lemma with specified gram. tags, eg. part-of-speech ("v"), the result table now lists frequency counts for all wordforms with a given lemma disregarding the features.

E.g. imagine real frequencies "kaja" 'v' 120, "kaja" 'n' 15.
Results now:
Searching 'v' > "kaja" 135
Searching 'n' > "kaja" 135

**Comment by timarkh** [comment]
Doesn't work for me. E.g. [here](http://multimedia-corpus.beserman.ru/search):
* Lemma *no*, Grammar *CONJ*: Frequency 315
* Lemma *no*, Grammar *PART*: Frequency 3599

Please provide steps to reproduce.

**Comment by sarkipo** [comment]
@timarkh For instance, in Dolgan: https://inel.corpora.uni-hamburg.de/DolganCorpus/search

- Lemma kaja, Grammar n (search lemmata): total frequency of found word forms: 35, frequency (in table): 266
- Lemma kaja, Grammar ~n (search lemmata): total frequency of found word forms: 231, frequency (in table): 266

**Comment by sarkipo** [comment]
![image](https://github.com/timarkh/tsakorpus/assets/11090777/19e27a0b-9428-4f77-8c2f-f67fe4c04561)

**Comment by timarkh** [comment]
As far as I can see, Tsakorpus version you are using there is two years old. Please update it and check if the problem persists.

**Comment by sarkipo** [comment]
Hmmm.-)
